title: ASI-403 Dart Interim Report
description: Dart project interim report
theme: just-the-docs

math: "mathjax"

plugins:
  - jekyll-redirect-from

url: https://nusrobomaster.github.io/dart-fyp

exclude:
  - docs/Dart Robot Subsystems.md
  - docs/Dart Robot - Launcher.md
  - docs/Dart Robot - Pitch Subsystem.md
  - docs/Dart Robot - Yaw Subsystem.md

aux_links:
  "ASI-403 Repo":
    - "https://github.com/nusrobomaster/Dart-FYP.git"
aux_links_new_tab: false